# Generated by Django 4.0 on 2021-12-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
