# Generated by Django 4.0 on 2021-12-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handsome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='handsome/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sabcategory',
            field=models.CharField(default='', max_length=70),
        ),
    ]
